export const FIREBASE_ENDPOINTS = {
  MASTER_DATA: "master_data",
  USER_WATCHLIST: "user_watchlist",
  USER_RM: "user_rm",
  USER_ROI: "user_roi",
  USER_TRADE_JOURNAL: "user_trade_journal",
  USER_AUTH: "user_register",
  USER_TRADE_SETTINGS: "user_trade_settings",
  USER_MANAGE_BROKERS: "user_manage_brokers",
  USER_MANAGE_DEMAT: "user_manage_demat",
  USER_MANAGE_STRATEGY: "user_manage_strategy",
  USER_SUBSCRIPTION: "user_subscription",
  MARKET_UPDATES_DATA: "update_info",
  USER_CUSTOM_BROKER_DATA: "user_custom_broker_data",
  CONTACT_US_DATA: "contact_us_data",
  PRICING_DATA: "subscription_plans",
};
