export const FIREBASE_ENDPOINTS = {
  MASTER_DATA: "users",
  USER_WATCHLIST: "watchlists",
  USER_TRADE_JOURNAL: "trades",
  USER_AUTH: "user_register",
  USER_MANAGE_STRATEGY: "strategies",
  USER_MANAGE_DEMAT: "demats",
  USER_MANAGE_BROKERS: "manage_brokers",
  USER_CUSTOM_BROKER_DATA: "custom_brokers",
  CONTACT_US_DATA: "tickets",
  RISK_MANAGE_DATA: "risks",
  USER_TRADE_SETTINGS: "user_trade_settings",
  MARKET_UPDATES_DATA: "update_info",
  PRICING_DATA: "subscription_plans",
};
